[2025-07-03T09:14:47.427+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: task_2_dag.extract manual__2025-07-03T09:14:45.841163+00:00 [queued]>
[2025-07-03T09:14:47.439+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: task_2_dag.extract manual__2025-07-03T09:14:45.841163+00:00 [queued]>
[2025-07-03T09:14:47.439+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-07-03T09:14:47.515+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract> on 2025-07-03 09:14:45.841163+00:00
[2025-07-03T09:14:47.521+0000] {standard_task_runner.py:60} INFO - Started process 228 to run task
[2025-07-03T09:14:47.525+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'task_2_dag', 'extract', 'manual__2025-07-03T09:14:45.841163+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/task_2_dag.py', '--cfg-path', '/tmp/tmp6n_6ypp5']
[2025-07-03T09:14:47.527+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask extract
[2025-07-03T09:14:47.587+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-03T09:14:47.626+0000] {task_command.py:423} INFO - Running <TaskInstance: task_2_dag.extract manual__2025-07-03T09:14:45.841163+00:00 [running]> on host b70660b8d774
[2025-07-03T09:14:47.834+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='task_2_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-07-03T09:14:45.841163+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-03T09:14:45.841163+00:00'
[2025-07-03T09:14:47.835+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: extract_data() missing 1 required positional argument: 'parquet_path'
[2025-07-03T09:14:47.848+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=task_2_dag, task_id=extract, execution_date=20250703T091445, start_date=20250703T091447, end_date=20250703T091447
[2025-07-03T09:14:47.994+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2 for task extract (extract_data() missing 1 required positional argument: 'parquet_path'; 228)
[2025-07-03T09:14:48.018+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-03T09:14:48.048+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
